"use client";

import { useEffect, useState } from "react";

type Task = { id: string; title: string; estimated_minutes: number; status: string };
type Block = { task_id: string; proposed_start: string; proposed_end: string; reasoning: string; conflict_flag: boolean };
type Plan = { id: string; status: string; baseline: { planned_blocks: Block[] }; proposal: { planned_blocks: Block[]; deferred_tasks: string[]; conflicted_tasks: string[]; fallback_reason?: string | null } };

export default function TodayPage() {
  const [tasks, setTasks] = useState<Task[]>([]); const [selected, setSelected] = useState<string[]>([]); const [plan, setPlan] = useState<Plan | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [approved, setApproved] = useState(false);
  useEffect(() => { fetch("/api/tasks").then(response => response.json()).then(setTasks).catch(() => setError("Could not load tasks.")); }, []);
  async function generate() { setLoading(true); setError(""); const response = await fetch("/api/plans/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date: new Date().toISOString().slice(0, 10), available_hours: 8, energy_level: "medium", task_ids: selected }) }); if (!response.ok) setError("Plan generation failed."); else setPlan(await response.json()); setLoading(false); }
  async function approve() { if (!plan || !window.confirm("Approve this plan?")) return; const response = await fetch(`/api/plans/${plan.id}/approve`, { method: "POST" }); if (!response.ok) setError("Approval failed."); else { setPlan(await response.json()); setApproved(true); } }
  async function reject() { if (!plan) return; const response = await fetch(`/api/plans/${plan.id}/reject`, { method: "POST" }); if (!response.ok) setError("Rejection failed."); else setPlan(await response.json()); }
  const title = (id: string) => tasks.find(task => task.id === id)?.title || id;
  return <main className="workspace"><header className="topbar"><div><span className="eyebrow">SCHEDULE REVIEW</span><h1>Today</h1></div><a className="primary-button" href="/capture">Capture</a></header><section className="panel-dark capture-panel"><div className="panel-heading"><div><span className="eyebrow">SELECT WORK</span><h3>Shape a plan you can keep</h3></div><button className="primary-button" disabled={loading || selected.length === 0} onClick={generate}>{loading ? "Generating..." : "Generate plan"}</button></div><div className="task-list">{tasks.filter(task => task.status !== "completed").map(task => <label className="task-row" key={task.id}><input type="checkbox" checked={selected.includes(task.id)} onChange={event => setSelected(current => event.target.checked ? [...current, task.id] : current.filter(id => id !== task.id))} /><div><strong>{task.title}</strong><small>{task.estimated_minutes} min</small></div></label>)}</div>{error && <p className="error">{error}</p>}</section>{plan && <><div className="dashboard-grid"><PlanColumn title="Deterministic baseline" blocks={plan.baseline.planned_blocks} taskTitle={title} /><PlanColumn title={`AI proposal · ${plan.proposal.fallback_reason ? "fallback" : "configured provider"}`} blocks={plan.proposal.planned_blocks} taskTitle={title} /></div><section className="panel-dark capture-panel"><p>{plan.proposal.deferred_tasks.length} deferred · {plan.proposal.conflicted_tasks.length} conflicted · status {approved ? "APPROVED" : plan.status}</p><div className="grid"><button className="primary-button" onClick={approve} disabled={approved}>Approve plan</button><button onClick={reject}>Reject plan</button></div></section></>}</main>;
}
function PlanColumn({ title, blocks, taskTitle }: { title: string; blocks: Block[]; taskTitle: (id: string) => string }) { return <section className="inbox-panel"><div className="section-title"><h3>{title}</h3></div>{blocks.map(block => <article className="task-row" key={block.task_id}><div><strong>{taskTitle(block.task_id)}</strong><small>{new Date(block.proposed_start).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} to {new Date(block.proposed_end).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}{block.conflict_flag ? " · conflict" : ""}</small><small>{block.reasoning}</small></div></article>)}</section>; }
